spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus
    username: root
    password: 12345678
    initialization-mode: always
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
