logging:
  level:
    root: info
    org.springframework: debug
    org.springframework.security: trace

spring:
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: 1
  application:
    admin:
      enabled: true
